services:
  grafana:
    container_name: monitoring_grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    depends_on:
      - prometheus
    links:
      - prometheus
    networks:
      - monitoring_net
    volumes:
      - grafana-data:/var/lib/grafana

  prometheus:
    container_name: monitoring_prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus
    networks:
      - monitoring_net

  node_exporter:
    container_name: monitoring_node_exporter
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks:
      - monitoring_net
      
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: monitoring_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    devices:
      - /dev/kmsg
    privileged: true
    networks:
      - monitoring_net
      
  alertmanager:
    image: prom/alertmanager:latest
    container_name: monitoring_alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    restart: always
    ports:
      - "9093:9093"
    networks:
      - monitoring_net
    labels:
      org.label-schema.group: "monitoring"

  versus-incident:
    image: ghcr.io/versuscontrol/versus-incident:latest
    container_name: monitoring_versus-incident
    ports:
      - "3001:3001"
    networks:
      - monitoring_net
    environment:
      - TELEGRAM_ENABLE=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./versus-incident/config/:/app/config/
    restart: unless-stopped

networks:
  monitoring_net:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data: